name: nostrawars
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  js: ^0.6.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg/
    - assets/icons/
