name: nostrawars
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  bech32: ^0.2.2
  bip340: ^0.1.0
  flame: ^1.6.0
  flame_audio: ^1.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.4
  hex: ^0.2.0
  uuid: ^3.0.7
  web_socket_channel: ^2.3.0
  kepler: ^1.0.3
  nostr: ^1.3.4
  pointycastle: ^3.7.0
  crypto: ^3.0.2
  js: ^0.6.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg/
    - assets/icons/
    - assets/images/
    - assets/audio/
